version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/app