services:
  - type: web
    name: knowledgerag-frontend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run frontend.py --server.port $PORT"
    plan: free
    healthCheckPath: "/"